filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "Gpqu*dcFn5fD2DCAUxS1"
setup.kibana:
  host: "localhost:5601"
